#!/bin/bash
#
# Copyright (c) 2015 University of Szeged.
# Copyright 2015 The Chromium Authors.
# All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#
# Kill a running Sprocket on Android
#
# Assumes you have sourced the build/android/envsetup.sh script.

adb shell am force-stop hu.uszeged.sprocket_apk
